// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtN4mx8lvNGKyJ5Od-BHqxyibyXrgYCD0',
    appId: '1:816159280151:web:f0dac64618cf67b0e86052',
    messagingSenderId: '816159280151',
    projectId: 'oneship-dfbab',
    authDomain: 'oneship-dfbab.firebaseapp.com',
    storageBucket: 'oneship-dfbab.firebasestorage.app',
    measurementId: 'G-SRHZ15QWFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA2G-VZi5h8_GDBr0ZmyErcTTvh0lnvSI',
    appId: '1:816159280151:android:86e133bf58c6b15fe86052',
    messagingSenderId: '816159280151',
    projectId: 'oneship-dfbab',
    storageBucket: 'oneship-dfbab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJtp8ndq2_IwqqVmDoLO_kMtXdk4eUJ_Q',
    appId: '1:816159280151:ios:55caab27f835b85de86052',
    messagingSenderId: '816159280151',
    projectId: 'oneship-dfbab',
    storageBucket: 'oneship-dfbab.firebasestorage.app',
    iosBundleId: 'com.oneship.merchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJtp8ndq2_IwqqVmDoLO_kMtXdk4eUJ_Q',
    appId: '1:816159280151:ios:32346b7fb81e646be86052',
    messagingSenderId: '816159280151',
    projectId: 'oneship-dfbab',
    storageBucket: 'oneship-dfbab.firebasestorage.app',
    iosBundleId: 'com.example.oneshipMerchantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtN4mx8lvNGKyJ5Od-BHqxyibyXrgYCD0',
    appId: '1:816159280151:web:284e08500eaf72bae86052',
    messagingSenderId: '816159280151',
    projectId: 'oneship-dfbab',
    authDomain: 'oneship-dfbab.firebaseapp.com',
    storageBucket: 'oneship-dfbab.firebasestorage.app',
    measurementId: 'G-0F2HE5YF2B',
  );
}